server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: nextlook-catalogo-categorias
              uri: lb://catalogo-ms
              predicates:
                - Path=/api/v1/categorias/**
            - id: nextlook-catalogo-productos
              uri: lb://catalogo-ms
              predicates:
                - Path=/api/v1/productos/**
            - id: nextlook-inventario
              uri: lb://inventario-ms
              predicates:
                - Path=/api/v1/inventario/**
            - id: nextlook-resenas
              uri: lb://resenas-ms
              predicates:
                - Path=/api/v1/resenas/**
            - id: nextlook-ordenes
              uri: lb://orden-ms
              predicates:
                - Path=/api/v1/ordenes/**
            - id: nextlook-pagos
              uri: lb://pago-ms
              predicates:
                - Path=/api/v1/pagos/**
            - id: nextlook-clientes
              uri: lb://cliente-ms
              predicates:
                - Path=/api/v1/clientes/**
            - id: nextlook-envios
              uri: lb://envio-ms
              predicates:
                - Path=/api/v1/envios/**
            - id: nextlook-notificaciones
              uri: lb://notificaciones-ms
              predicates:
                - Path=/api/v1/notificaciones/**

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: http://nextlook-eureka:8761/eureka

management:
  endpoint:
    health:
      show-details: never
